// 8 < 6 FALSE  - MENOR
// 7 > 5 TRUE   - MAIOR
// 8 >= 8 TRUE  - MAIOR OR IGUAL
// 9 <= 6 FALSE - MENOR OU IGUAL
// 7 == 7 TRUE  - IGUAL 
// 5 != 8 TRUE  - DIFETENTE
// 5 === "5" FALSE - IDENTICO (ESSE TESTA SE O VALOR É IGUAL E TBM O TYPE DELE)
// 5 !== "5" TRUE - DESIGUAL (ESSE TESTA SE O VALOR É IGUAL E TBM O TYPE DELE)